### ISSUE TITLE
The Implementation of Region Feature Extraction

### ISSUE THREAD

**Issue by maktu6** [zxhuang1698/interpretability-by-parts#3]
Dose the implementation of Region Feature Extraction in [here](https://github.com/zxhuang1698/interpretability-by-parts/blob/master/src/grouping.py#L72-L91) equal to Equation(3) in the paper,  Can you explain it more concretely? And what is the difference of just using `qx = torch.bmm(assign, x)` as the `out`, dose the model performance would degrade?

**Comment by zxhuang1698** [comment]
Yes, I think so. Please see the updated comments of that file. For computing the residual coding, note that the grouping centers do not need to go through the \sum{q_ij d} / \sum{q_ij} step because \sum{q_ij d} = \sum{q_ij} * d.

For residual coding, we follow the commonly used nonlinear feature encoding scheme. You can definitely try to remove the residual term, it might hurt the accuracy to some extent. But I think you still need the normalization term to make the magnitude consistent.

**Comment by maktu6** [comment]
Thanks for your reply!
